name: Backend CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: auto_saas
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: your_password_here
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
    - name: Test Build
      run: echo "✅ Build Passed!"
